### ISSUE TITLE
is there an option to not render joints ? 

### ISSUE THREAD

**Issue by cfournel** [rkn14/as3-bvh-parser#1]
Hey, 

first of all , thank you for sharing this ( i was lazy to start reading bvh manual ) .

i m currently having my own awd mesh ready to be animate with a awdskeleton , i m wondering if there is a way to read my bvh animation with you code and integrate it directly to my mesh.

of course i need to not render joints

**Comment by rkn14** [comment]
Hi,

Yes, it's your job to implement your own rendering. So you can render or not joints.

Have a look to the example : 
https://github.com/rkn14/as3-bvh-parser/blob/master/examples/src/org/rkn14/bvh/examples/away3d/Away3DBvhObject.as
see the drawJoints function ;)

have fun !

**Comment by cfournel** [comment]
i m so sorry to bother you :)
next time i ll search for more before whinning :D :+1:

**Comment by rkn14** [comment]
happy to see someone using this lib :)
You can either render only joints, like in this little demo i made 3 years ago
http://rkn14.com/wordpress/salsa-pumpkin-a-small-stage3d-demo-using-away3d-4-bvh-and-physics/

**Comment by cfournel** [comment]
yeah i was looking for something like this , since we are working on a mobile app with multiple mesh that should handle thousands of animation....

including all of them in awd file is too large and the app can t even load one
